# Generated by Django 3.0.5 on 2020-04-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200427_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='shortname',
            new_name='short_name',
        ),
    ]
