# Generated by Django 3.0.5 on 2020-04-27 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200427_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='parallel',
        ),
        migrations.AddField(
            model_name='grade',
            name='entry_year',
            field=models.IntegerField(default=2010),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.School'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClassesParallel',
        ),
    ]
