# Generated by Django 3.0.5 on 2020-04-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200428_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
