# Generated by Django 3.0.5 on 2020-04-27 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200427_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulelesson',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedulelesson',
            name='place',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schedule.Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='schedulelesson',
            name='schedule_day',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.ScheduleDay'),
            preserve_default=False,
        ),
    ]
