# Generated by Django 3.0.5 on 2020-04-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_subject'),
        ('tasks', '0002_auto_20200427_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Grade'),
            preserve_default=False,
        ),
    ]
