# Generated by Django 3.0.5 on 2020-04-27 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_subject'),
        ('tasks', '0003_task_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Grade'),
        ),
    ]
