# Generated by Django 3.0.5 on 2020-04-27 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200428_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='grade',
        ),
    ]
