# Generated by Django 3.0.5 on 2020-04-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200428_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lesson',
        ),
    ]
