# Generated by Django 3.0.5 on 2020-04-28 07:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_remove_task_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 10, 55, 19, 354192)),
        ),
        migrations.AddField(
            model_name='task',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='task', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Grade'),
        ),
    ]
