# Generated by Django 3.0.5 on 2020-04-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20200428_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.Task'),
            preserve_default=False,
        ),
    ]
