# Generated by Django 3.0.5 on 2020-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backSchool', '0003_remove_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
