# Generated by Django 3.0.5 on 2020-04-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200427_1826'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='schedule_lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.ScheduleLesson'),
            preserve_default=False,
        ),
    ]
